### ISSUE TITLE
Populate Projects Section with the following "Product Map" 

### ISSUE THREAD

**Issue by claudiosanchez** [CaribbeanDevelopersConference/ConferenceApp#2]
# DevOps
    - Get App building and deploying 
    to AppCenter.
    - Create Distribution Lists 
    - Extend Pipeline to Stores (TestFlight)
    - Create Azure DevOps instance
        - Grant access to Contributors
            
# App
    - Create Speakers Screen (List)
        - Handle Navigation to Empty page
        - Create Page Skeleton
        - Create ViewModel
        - Mock Some Data
        - Work on the Item Template
    - Create Speaker Detail  (Detail)
        - Handle Navigation to Empty page
        - Create Page Skeleton
        - Create ViewModel
        - Mock Some Data
        - Work on Screen layout
    - Create Schedule Screen (List)
        - Handle Navigation to Empty page
        - Create Page Skeleton
        - Create ViewModel
        - Mock Some Data
        - Work on the Item Template
    - Create Session Screen (Detail)
        - Handle Navigation to Empty page
        - Create Page Skeleton
        - Create ViewModel
        - Mock Some Data
        - Work on Screen layout
    - Create a Favorites Screen (List)
        - Handle Navigation to Empty page
        - Create Page Skeleton
        - Create ViewModel
        - Mock Some Data
        - Work on the Item Template
    - Add the ability to add a session to Favorites
    - Add the ability to remove a session from Favorites
       
# UI/UX

# Backend
    Consume the data RAW from Sessionize

# UI Testing
    - Page Object Model based UI Testing.
    https://channel9.msdn.com/Shows/XamarinShow/Best-Practices-for-User-Interface-Automation

**Comment by RLittlesII** [comment]
@claudiosanchez All the items except the UI Testing have been converted to issues.  I would say we could have ui testing issue per screen in the future.
